export const Genero = {
    "alt": "ALTERNATIVE",
    "alt_dance": "ALTERNATIVE ROCK / ALTERNATIVE DANCE",
    "alt_brit": "ALTERNATIVE ROCK / BRITISH ALTERNATIVE",
    "alt_exp": "ALTERNATIVE ROCK / EXPERIMENTAL ROCK",
    "alt_garage": "ALTERNATIVE ROCK / GARAGE ROCK",
    "alt_goth": "ALTERNATIVE ROCK / GOTH & INDUSTRIAL",
    "alt_grunge": "ALTERNATIVE ROCK / GRUNGE",
    "alt_hard": "ALTERNATIVE / PUNK",
    "alt_indie": "ALTERNATIVE / INDIE ROCK",
    "alt_new": "ALTERNATIVE ROCK / NEW WAVE & POST-PUNK",
    "alt_noise": "ALTERNATIVE ROCK / NOISE",
    "alt_singer": "ALTERNATIVE ROCK / SINGER-SONGWRITERS",
    "alt_ska": "ALTERNATIVE ROCK / SKA",
    "alt_space": "ALTERNATIVE ROCK / SPACE ROCK",
    "blues": "BLUES",
    "blues_accoustic": "BLUES / ACOUSTIC BLUES",
    "blues_chicago": "BLUES / CHICAGO BLUES",
    "blues_classical": "BLUES / CLASSICAL FEMALE VOCAL BLUES",
    "blues_cont": "BLUES / CONTEMPORARY BLUES",
    "blues_delta": "BLUES / DELTA BLUES",
    "blues_elec": "BLUES / ELECTRIC BLUES GUITAR",
    "blues_mod": "BLUES / MODERN BLUES",
    "blues_reg": "BLUES / REGIONAL BLUES",
    "blues_trad": "BLUES / TRADITIONAL BLUES",
    "bway": "BROADWAY & VOCALISTS",
    "bway_trad": "BROADWAY & VOCALISTS / TRADITIONAL VOCAL POP",
    "bway_cab": "BROADWAY & VOCALISTS / CABARET",
    "bway_class": "BROADWAY & VOCALISTS / CLASSIC VOCALISTS",
    "bway_musical": "BROADWAY & VOCALISTS / MUSICALS",
    "child": "CHILDRENS MUSIC",
    "childs": "CHILDREN'S MUSIC",
    "child_barney": "CHILDRENS MUSIC / BARNEY",
    "child_cartoon": "CHILDRENS MUSIC / CARTOON MUSIC",
    "child_disney": "CHILDRENS MUSIC / DISNEY",
    "child_disneys": "CHILDREN'S MUSIC/DISNEY",
    "child_edu": "CHILDRENS MUSIC / EDUCATIONAL",
    "child_lull": "CHILDRENS MUSIC / LULLABIES",
    "child_music": "CHILDRENS MUSIC / MUSIC FOR LITTLE PEOPLE",
    "child_pokemon": "CHILDRENS MUSIC / POKEMON",
    "child_sesame": "CHILDRENS MUSIC / SESAME STREET",
    "gospel": "CHRISTIAN & GOSPEL",
    "gospel_alt": "HOLIDAY / CHANUKAH",
    "gospel_cont": "CHRISTIAN & GOSPEL / CHRISTIAN CONTEMPORARY MUSIC",
    "gospel_rap": "HOLIDAY / EASTER",
    "gospel_rock": "HOLIDAY / HALLOWEEN",
    "gospel_country": "HOLIDAY / CHRISTMAS",
    "gospel_gospel": "HOLIDAY / THANKSGIVING",
    "gospel_praise": "CHRISTIAN & GOSPEL / PRAISE & WORSHIP",
    "classrock": "CLASSIC ROCK",
    "classrock_aor": "CLASSIC ROCK / ALBUM-ORIENTED ROCK (AOR)",
    "classrock_arena": "CLASSIC ROCK / ARENA ROCK",
    "classrock_brit": "CLASSIC ROCK / BRITISH INVASION",
    "classrock_glam": "CLASSIC ROCK / GLAM",
    "classrock_psych": "CLASSIC ROCK / PSYCHEDELIC ROCK",
    "classrock_south": "CLASSIC ROCK / SOUTHERN ROCK",
    "classrock_super": "CLASSIC ROCK / SUPERGROUPS",
    "class": "CLASSICAL",
    "class_baroque": "CLASSICAL / BAROQUE (C. 1600-1750)",
    "class_chamber": "CLASSICAL / CHAMBER MUSIC",
    "class_class": "CLASSICAL / CLASSICAL (C. 1770-1830)",
    "class_crossover": "CLASSICAL / CLASSICAL CROSSOVER",
    "class_early": "CLASSICAL / EARLY MUSIC",
    "class_modern": "CLASSICAL / MODERN, 20TH, & 21ST CENTURY",
    "class_rena": "CLASSICAL / RENAISSANCE (C. 1450-1600)",
    "class_romantic": "CLASSICAL / ROMANTIC (C. 1820-1910)",
    "class_sacred": "CLASSICAL / SACRED & RELIGIOUS",
    "class_symph": "CLASSICAL / SYMPHONIES",
    "country": "COUNTRY",
    "country_alt": "COUNTRY / ALT-COUNTRY & AMERICANA",
    "country_gospel": "COUNTRY / COUNTRY GOSPEL",
    "country_cowboy": "COUNTRY / COWBOY",
    "country_honky": "COUNTRY / HONKY-TONK",
    "country_outlaw": "COUNTRY / OUTLAW & PROGRESSIVE COUNTRY",
    "country_trad": "COUNTRY / TRADITIONAL COUNTRY",
    "country_west": "COUNTRY / WESTERN SWING",
    "dance": "DANCE",
    "dance_amb": "DANCE & DJ / AMBIENT",
    "dance_big": "DANCE & DJ / BIG BEAT",
    "dance_pop": "DANCE & DJ / DANCE POP",
    "dance_disco": "DANCE & DJ / DISCO",
    "dance_drum": "DANCE & DJ / DRUM & BASS",
    "dance_elec": "ELECTRONIC",
    "dance_free": "DANCE & DJ / FREESTYLE",
    "dance_house": "DANCE & DJ / HOUSE",
    "dance_idm": "DANCE & DJ / IDM",
    "dance_indust": "WORLD / FRANCE",
    "dance_tech": "INSTRUMENTAL",
    "dance_tran": "DANCE & DJ / TRANCE",
    "dance_trip": "DANCE & DJ / TRIP-HOP",
    "dance_turn": "DANCE & DJ / TURNTABLISTS",
    "dance_world": "WORLD",
    "folk": "FOLK",
    "folk_cont": "FOLK / CONTEMPORARY FOLK",
    "folk_jewish": "FOLK / JEWISH & YIDDISH MUSIC",
    "folk_brit": "FOLK / TRADITIONAL BRITISH & CELTIC FOLK",
    "folk_trad": "FOLK / TRADITIONAL FOLK",
    "hard": "HARD ROCK & METAL",
    "hard_alt": "HARD ROCK & METAL / ALTERNATIVE METAL",
    "hard_brit": "HARD ROCK & METAL / BRITISH METAL",
    "hard_death": "HARD ROCK & METAL / DEATH METAL",
    "hard_hard": "HARD ROCK & METAL / HARD ROCK",
    "hard_pop": "HARD ROCK & METAL / POP METAL",
    "hard_thrash": "HARD ROCK & METAL / THRASH & SPEED METAL",
    "inter": "INTERNATIONAL",
    "inter_afri": "INTERNATIONAL / AFRICA",
    "inter_aust": "INTERNATIONAL / AUSTRALIA & NEW ZEALAND",
    "inter_cajun": "INTERNATIONAL / CAJUN & ZYDECO",
    "inter_carib": "INTERNATIONAL / CARIBBEAN & CUBA",
    "inter_celt": "INTERNATIONAL / CELTIC",
    "inter_euro": "GERMAN POP",
    "inter_asia": "CHINESE",
    "inter_india": "INDIAN",
    "inter_latin": "INTERNATIONAL / LATIN MUSIC",
    "inter_mexi": "INDIAN / TELUGU",
    "inter_mideast": "ARABIC",
    "inter_noramer": "INTERNATIONAL / NORTH AMERICA",
    "inter_pacific": "INTERNATIONAL / PACIFIC ISLANDS",
    "inter_reggae": "REGGAE",
    "inter_souamer": "INTERNATIONAL / SOUTH & CENTRAL AMERICA",
    "jazz": "JAZZ",
    "jazz_acid": "JAZZ / ACID JAZZ",
    "jazz_avant": "JAZZ / AVANT GARDE & FREE JAZZ",
    "jazz_bebop": "JAZZ / BEBOP",
    "jazz_brazil": "BRAZILIAN",
    "brazilian_black": "BRAZILIAN / BLACK MUSIC",
    "brazilian_folc": "BRAZILIAN / FOLCLORICA",
    "brazilian_rom": "BRAZILIAN / ROMANTICA",
    "brazilian_inf": "BRAZILIAN / INFANTIL",
    "brazilian_samba": "BRAZILIAN / SAMBA",
    "brazilian_ragod": "BRAZILIAN / PAGODE",
    "brazilian_gosp": "BRAZILIAN / GOSPEL",
    "brazilian_elect": "BRAZILIAN / ELECTRONICA",
    "brazilian_funk": "BRAZILIAN / FUNK BRASILEIRO",
    "brazilian_sert": "BRAZILIAN / SERTANEJO",
    "brazilian_mpb": "BRAZILIAN / MPB",
    "brazilian_axe": "BRAZILIAN / AXE",
    "brazilian_bossa": "BRAZILIAN / BOSSA NOVA",
    "brazilian_forro": "BRAZILIAN / FORRO",
    "brazilian_brega": "BRAZILIAN / BREGA",
    "jazz_cool": "JAZZ / COOL JAZZ",
    "jazz_fus": "JAZZ / JAZZ FUSION",
    "jazz_jam": "MARCHING BANDS",
    "jazz_latin": "JAZZ / LATIN JAZZ",
    "jazz_mod": "JAZZ / MODERN POSTBEBOP",
    "jazz_orleans": "JAZZ / NEW ORLEANS JAZZ",
    "jazz_smooth": "JAZZ / SMOOTH JAZZ",
    "jazz_soul": "JAZZ / SOUL-JAZZ & BOOGALOO",
    "jazz_swing": "JAZZ / SWING JAZZ",
    "jazz_trad": "JAZZ / TRADITIONAL JAZZ & RAGTIME",
    "jazz_vocal": "VOCAL",
    "latin": "LATIN",
    "latin_bach": "LATIN MUSIC / BACHATA",
    "latin_band": "LATIN MUSIC / BANDA",
    "latin_big": "LATIN MUSIC / BIG BAND",
    "latin_bole": "LATIN MUSIC / BOLERO",
    "latin_corr": "LATIN MUSIC / CORRIDOS",
    "latin_dura": "LATIN MUSIC / DURANGUENCE",
    "latin_flam": "LATIN MUSIC / FLAMENCO",
    "latin_grup": "LATIN MUSIC / GRUPERO",
    "latin_pop": "LATIN MUSIC / LATIN POP",
    "latin_rap": "LATIN MUSIC / LATIN RAP",
    "latin_mamb": "LATIN MUSIC / MAMBO",
    "latin_mari": "LATIN MUSIC / MARIACHI",
    "latin_mere": "LATIN MUSIC / MERENGUE",
    "latin_nort": "LATIN MUSIC / NORTENO",
    "latin_ranch": "LATIN MUSIC / RANCHERA",
    "latin_ranchs": "LATIN MUSIC/RANCHERA",
    "latin_rock": "LATIN MUSIC / ROCK EN ESPANOL",
    "latin_salsa": "LATIN / REGIONAL MEXICANO",
    "latin_sonid": "LATIN MUSIC / SONIDERO",
    "latin_tango": "LATIN MUSIC / TANGO",
    "latin_teja": "LATIN MUSIC / TEJANO",
    "lounge": "EASY LISTENING / LOUNGE",
    "newage": "NEW AGE",
    "newage_celt": "WORLD / CELTIC",
    "newage_env": "NEW AGE / ENVIRONMENTAL",
    "newage_heal": "NEW AGE / HEALING",
    "newage_medit": "NEW AGE / MEDITATION",
    "opera": "OPERA",
    "opera_arias": "OPERA & VOCAL / ARIAS",
    "opera_baroq": "OPERA & VOCAL / BAROQUE (C. 1600-1750)",
    "opera_class": "OPERA & VOCAL / CLASSICAL (C. 1770-1830)",
    "opera_early": "OPERA & VOCAL / EARLY MUSIC",
    "opera_mod": "OPERA & VOCAL / MODERN & 20TH CENTURY",
    "opera_operet": "CLASSICAL / OPERA",
    "opera_orat": "OPERA & VOCAL / ORATORIOS",
    "opera_rena": "OPERA & VOCAL / RENAISSANCE (C. 1450-1600)",
    "opera_romantic": "OPERA & VOCAL / ROMANTIC (C. 1820-1910)",
    "opera_vocal": "ORCHESTRAL",
    "pop": "POP",
    "pop_adult": "POP / ADULT ALTERNATIVE",
    "pop_cont": "J-POP",
    "pop_easy": "EASY LISTENING",
    "pop_euro": "FRENCH POP",
    "pop_oldies": "POP / OLDIES",
    "pop_rock": "K-POP",
    "pop_singer": "POP / SINGER-SONGWRITERS",
    "pop_soft": "POP / SOFT ROCK",
    "pop_teen": "POP / TEEN POP",
    "randb": "R&B",
    "randb_class": "R&B / CLASSIC R&B",
    "randb_cont": "R&B / CONTEMPORARY R&B",
    "randb_funk": "R&B / FUNK",
    "randb_mo": "R&B / MOTOWN",
    "randb_neo": "R&B / NEO-SOUL",
    "randb_newjack": "R&B / NEW JACK",
    "randb_qs": "R&B / QUIET STORM",
    "randb_soul": "R&B/SOUL",
    "rap": "HIP HOP/RAP",
    "rap_bass": "RAP & HIP-HOP / BASS",
    "rap_east": "RAP & HIP-HOP / EAST COAST",
    "rap_exp": "RAP & HIP-HOP / EXPERIMENTAL RAP",
    "rap_gang": "RAP & HIP-HOP / GANGSTA & HARDCORE",
    "rap_int": "RAP & HIP-HOP / INTERNATIONAL RAP",
    "rap_old": "RAP & HIP-HOP / OLD SCHOOL",
    "rap_pop": "RAP & HIP-HOP / POP RAP",
    "rap_south": "RAP & HIP-HOP / SOUTHERN RAP",
    "rap_west": "RAP & HIP-HOP / WEST COAST",
    "rock": "ROCK",
    "rock_blues": "ROCK / BLUES ROCK",
    "rock_country": "ROCK / COUNTRY ROCK",
    "rock_folk": "ROCK / FOLK ROCK",
    "rock_funk": "ROCK / FUNK ROCK",
    "rock_jam": "ROCK / JAM BANDS",
    "rock_oldies": "ROCK / OLDIES & RETRO",
    "rock_power": "ROCK / POWER POP",
    "rock_prog": "ROCK / PROGRESSIVE",
    "rock_rap": "ROCK / RAP ROCK",
    "rock_roots": "ROCK / ROOTS ROCK",
    "rock_singer": "ROCK / SINGER-SONGWRITER",
    "singer_song": "SINGER/SONGWRITER",
    "sndtrck": "SOUNDTRACK",
    "sndtrck_anime": "ANIME",
    "sndtrck_score": "SOUNDTRACKS / MOVIE SCORES",
    "sndtrck_movie": "SOUNDTRACKS / MOVIE SOUNDTRACKS",
    "sndtrck_tv": "SOUNDTRACKS / TELEVISION SOUNDTRACKS",
    "misc": "MISCELLANEOUS",
    "misc_anim": "MISCELLANEOUS / ANIMAL SOUNDS",
    "misc_comedy": "COMEDY",
    "misc_exer": "FITNESS & WORKOUT",
    "misc_exp": "MISCELLANEOUS / EXPERIMENTAL MUSIC",
    "misc_gay": "MISCELLANEOUS / GAY & LESBIAN",
    "misc_holi": "HOLIDAY",
    "misc_instr": "INSPIRATIONAL",
    "misc_kara": "KARAOKE",
    "misc_march": "MISCELLANEOUS / MARCHES",
    "misc_nost": "MISCELLANEOUS / NOSTALGIA",
    "misc_poet": "MISCELLANEOUS / POETRY, SPOKEN WORD & INTERVIEWS",
    "misc_polka": "MISCELLANEOUS / POLKA",
    "misc_self": "MISCELLANEOUS / SELF-HELP",
    "misc_sound": "SOUNDTRACK / SOUND EFFECTS",
    "misc_test": "MISCELLANEOUS / TEST RECORDING",
    "misc_wedd": "MISCELLANEOUS / WEDDING MUSIC",
    "spoken_radio": "SPOKEN WORD",
    "world_asia": "WORLD / ASIA",
    "world_hawaii": "WORLD / HAWAII"
};